const products = {
    1: {
        1: {
            name: "Wooden Chair",
            subHeader: "VISIT CHAIR STORE",
            subHeaderLink: "../products_1.html",
            rating: 3.5,
            oldPrice: 10,
            newPrice: 8,
            color: "Brown",
            Available: true,
            Category: "Chair",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/chair1-1.jpg"],
            about: "This is a wooden chair",
        },
        2: {
            name: "Wheel chair",
            subHeader: "VISIT CHAIR STORE",
            subHeaderLink: "../products_1.html",
            rating: 4,
            oldPrice: 12,
            newPrice: 10,
            color: "Coffee",
            Available: true,
            Category: "Chair",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/chair2.jpg"],
            about: "This is a wheel chair",
        },
        3: {
            name: "ًWooden set",
            subHeader: "VISIT CHAIR STORE",
            subHeaderLink: "../products_1.html",
            rating: 5,
            oldPrice: 15,
            newPrice: 12,
            color: "Brown",
            Available: true,
            Category: "Chair",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/chair3.jpg"],
            about: "This is a wooden set",
        },
        4: {
            name: "Small chair",
            subHeader: "VISIT CHAIR STORE",
            subHeaderLink: "../products_1.html",
            rating: 2.5,
            oldPrice: 15,
            newPrice: 12,
            color: "Coffee",
            Available: true,
            Category: "Chair",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/chair4.jpg"],
            about: "This is a small chair",
        },
        5: {
            name: "Modern Chair",
            subHeader: "VISIT CHAIR STORE",
            subHeaderLink: "../products_1.html",
            rating: 4.5,
            oldPrice: 19,
            newPrice: 17,
            color: "Brown",
            Available: true,
            Category: "Chair",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/chair5.jpg"],
            about: "This is a modern chair",
        },
        6: {
            name: "Comfortable chair",
            subHeader: "VISIT CHAIR STORE",
            subHeaderLink: "../products_1.html",
            rating: 4,
            oldPrice: 18,
            newPrice: 16,
            color: "Gray",
            Available: true,
            Category: "Chair",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/chair6.jpg"],
            about: "This is a wooden table",
        },
        7: {
            name: "New woodem chair",
            subHeader: "VISIT CHAIR STORE",
            subHeaderLink: "../products_1.html",
            rating: 5,
            oldPrice: 10,
            newPrice: 18,
            color: "Orange",
            Available: true,
            Category: "Chair",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/chair7.jpg"],
            about: "This is a wooden table",
        },
        8: {
            name: "White wooden chair",
            subHeader: "VISIT CHAIR STORE",
            subHeaderLink: "../products_1.html",
            rating: 2,
            oldPrice: 22,
            newPrice: 17,
            color: "White",
            Available: true,
            Category: "Chair",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/chair8.jpg"],
            about: "This is a wooden table",
        },
    },
    2: {
        1: {
            name: "Blue jacket",
            subHeader: "VISIT JACKET STORE",
            subHeaderLink: "../products_2.html",
            rating: 5,
            oldPrice: 5,
            newPrice: 4,
            color: "Blue",
            Available: true,
            Category: "Jacket",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Jacket 1.jpg"],
            about: "This is a Blue Jacket",
        },
        2: {
            name: "Brown jacket",
            subHeader: "VISIT JACKET STORE",
            subHeaderLink: "../products_2.html",
            rating: 4,
            oldPrice: 6,
            newPrice: 5,
            color: "Brown",
            Available: true,
            Category: "Jacket",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Jacket 2.jpg"],
            about: "This is a Brown Jacket",
        },
        3: {
            name: "ًGreen jacket",
            subHeader: "VISIT JACKET STORE",
            subHeaderLink: "../products_2.html",
            rating: 3.5,
            oldPrice: 7.5,
            newPrice: 7,
            color: "Green",
            Available: true,
            Category: "Jacket",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Jacket 3.jpg"],
            about: "This is a Green Jacket",
        },
        4: {
            name: "Pink jacket",
            subHeader: "VISIT JACKET STORE",
            subHeaderLink: "../products_2.html",
            rating: 2.5,
            oldPrice: 5.5,
            newPrice: 4,
            color: "Pink",
            Available: true,
            Category: "Jacket",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Jacket 4.jpg"],
            about: "This is a Pink Jacket",
        },
        5: {
            name: "Gray jacket",
            subHeader: "VISIT JACKET STORE",
            subHeaderLink: "../products_2.html",
            rating: 4.5,
            oldPrice: 10,
            newPrice: 7,
            color: "Gray",
            Available: true,
            Category: "Jacket",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Jacket 5.jpg"],
            about: "This is a Green Jacket",
        },
        6: {
            name: "Jeans jacket",
            subHeader: "VISIT JAKCET STORE",
            subHeaderLink: "../products_2.html",
            rating: 4,
            oldPrice: 11,
            newPrice: 10,
            color: "Jeans",
            Available: true,
            Category: "Jacket",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Jacket 6.jpg"],
            about: "This is a Jeans Jacket",
        },
        7: {
            name: "Jeans jacket",
            subHeader: "VISIT JACKET STORE",
            subHeaderLink: "../products_2.html",
            rating: 5,
            oldPrice: 15,
            newPrice: 14,
            color: "Jeans",
            Available: true,
            Category: "Jacket",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Jacket 7.jpg"],
            about: "This is a Jeans Jacke",
        },
        8: {
            name: "Black jacket",
            subHeader: "VISIT JACKET STORE",
            subHeaderLink: "../products_2.html",
            rating: 2.5,
            oldPrice: 10,
            newPrice: 8,
            color: "Black",
            Available: true,
            Category: "Jacket",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Jacket (2).jpg"],
            about: "This is a Black Jacket",
        },
    },
    3: {
        1: {
            name: "Table 1",
            subHeader: "VISIT TABLE STORE",
            subHeaderLink: "../products_3.html",
            rating: 3.5,
            oldPrice: 5,
            newPrice: 4,
            color: "Brown",
            Available: true,
            Category: "Table",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Table 1.jpg"],
            about: "This is a table",
        },
        2: {
            name: "Table 2",
            subHeader: "VISIT TABLE STORE",
            subHeaderLink: "../products_3.html",
            rating: 4,
            oldPrice: 6,
            newPrice: 5,
            color: "Brown",
            Available: true,
            Category: "Table",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Table 2.jpg"],
            about: "This is a talbe",
        },
        3: {
            name: "ًTable 3",
            subHeader: "VISIT TABLE STORE",
            subHeaderLink: "../products_3.html",
            rating: 3.5,
            oldPrice: 7.5,
            newPrice: 7,
            color: "Brown",
            Available: true,
            Category: "Table",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Table 3.jpg"],
            about: "This is a table",
        },
        4: {
            name: "Table 4",
            subHeader: "VISIT TABLE STORE",
            subHeaderLink: "../products_3.html",
            rating: 2.5,
            oldPrice: 5.5,
            newPrice: 4,
            color: "Brown",
            Available: true,
            Category: "Table",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Table 4.jpg"],
            about: "This is a table",
        },
        5: {
            name: "Table 5",
            subHeader: "VISIT TABLE STORE",
            subHeaderLink: "../products_3.html",
            rating: 4.5,
            oldPrice: 10,
            newPrice: 7,
            color: "Brown",
            Available: true,
            Category: "Table",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Table 5.jpg"],
            about: "This is a table",
        },
        6: {
            name: "Table 6",
            subHeader: "VISIT TABLE STORE",
            subHeaderLink: "../products_3.html",
            rating: 4,
            oldPrice: 11,
            newPrice: 10,
            color: "Brown",
            Available: true,
            Category: "Table",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Table 6.jpg"],
            about: "This is a table",
        },
        7: {
            name: "Table 7",
            subHeader: "VISIT TABLE STORE",
            subHeaderLink: "../products_3.html",
            rating: 5,
            oldPrice: 15,
            newPrice: 14,
            color: "Brown",
            Available: true,
            Category: "Table",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Table 7.jpg"],
            about: "This is a table",
        },
        8: {
            name: "Table 8",
            subHeader: "VISIT TABLE STORE",
            subHeaderLink: "../products_3.html",
            rating: 2.5,
            oldPrice: 10,
            newPrice: 8,
            color: "Brown",
            Available: true,
            Category: "Table",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Table 8.jpg"],
            about: "This is a table",
        },
    },
    4: {
        1: {
            name: "Iphone XS Max",
            subHeader: "VISIT IPHONE STORE",
            subHeaderLink: "../products_4.html",
            rating: 4,
            oldPrice: 100,
            newPrice: 170,
            color: "Gold",
            Available: true,
            Category: "Iphone",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Iphone 1.webp"],
            about: "Iphone XS Max with 4G + 4GRAM",
        },
        2: {
            name: "Iphone 12 pro max",
            subHeader: "VISIT IPHIONE STORE",
            subHeaderLink: "../products_4.html",
            rating: 4.4,
            oldPrice: 440,
            newPrice: 430,
            color: "Blue",
            Available: true,
            Category: "Iphone",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Iphone 2.jpg"],
            about: "Iphone 12 pro max with 128G + 8GRAM",
        },
        3: {
            name: "ًIphone 12",
            subHeader: "VISIT IPHONE STORE",
            subHeaderLink: "../products_4.html",
            rating: 4,
            oldPrice: 400,
            newPrice: 390,
            color: "Black",
            Available: true,
            Category: "Iphine",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Iphone 3.jpg"],
            about: "Iphone 12 with 64G + 4GRAM",
        },
        4: {
            name: "Iphone 14",
            subHeader: "VISIT IPHONE STORE",
            subHeaderLink: "../products_4.html",
            rating: 4.8,
            oldPrice: 500,
            newPrice: 480,
            color: "White",
            Available: true,
            Category: "Iphone",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Iphone 4.webp"],
            about: "Iphone 14 with 256G + 8GRAM",
        },
        5: {
            name: "Iphone 14 pro max",
            subHeader: "VISIT IPHONE STORE",
            subHeaderLink: "../products_4.html",
            rating: 5,
            oldPrice: 550,
            newPrice: 530,
            color: "Silver",
            Available: true,
            Category: "Iphone",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Iphone 5.webp"],
            about: "Iphone 14 pro max with 128G + 8GRAM",
        },
        6: {
            name: "Iphone 15 pro max",
            subHeader: "VISIT IPHONE STORE",
            subHeaderLink: "../products_4.html",
            rating: 5,
            oldPrice: 600,
            newPrice: 580,
            color: "Blue",
            Available: true,
            Category: "Iphone",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Iphone 6.webp"],
            about: "Iphone 15 pro max with 256G + 16GRAM",
        },
        7: {
            name: "Iphone 15",
            subHeader: "VISIT IPHONE STORE",
            subHeaderLink: "../products_4.html",
            rating: 4,
            oldPrice: 400,
            newPrice: 390,
            color: "Black",
            Available: true,
            Category: "Iphone",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Iphone (2).jpg"],
            about: "Iphone 15 with 128G + 8GRAM",
        },
        8: {
            name: "Iphone 13 pro max",
            subHeader: "VISIT IPHONE STORE",
            subHeaderLink: "../products_4.html",
            rating: 3.8,
            oldPrice: 460,
            newPrice: 440,
            color: "Gray",
            Available: true,
            Category: "Iphone",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Iphone 8.jpg"],
            about: "Iphone 13 pro max with 128G + 8GRAM",
        },
    },
    5: {
        1: {
            name: "legion laptop",
            subHeader: "VISIT laptop STORE",
            subHeaderLink: "../products_5.html",
            rating: 4,
            oldPrice: 1100,
            newPrice: 1000,
            color: "silver",
            Available: true,
            Category: "laptop",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/lap (2).jpg"],
            about: "work station laptop",
        },
        2: {
            name: "Apple laptop",
            subHeader: "VISIT laptop STORE",
            subHeaderLink: "../products_5.html",
            rating: 4.4,
            oldPrice: 600,
            newPrice: 550,
            color: "silver",
            Available: true,
            Category: "laptop",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/lap (3).jpg"],
            about: "small version of apple laptop",
        },
        3: {
            name: "ًdell laptop",
            subHeader: "VISIT laptop STORE",
            subHeaderLink: "../products_5.html",
            rating: 4,
            oldPrice: 800,
            newPrice: 750,
            color: "Black",
            Available: true,
            Category: "laptop",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/lap (4).jpg"],
            about: "for business",
        },
        4: {
            name: "apple laptop",
            subHeader: "VISIT laptop STORE",
            subHeaderLink: "../products_5.html",
            rating: 4.8,
            oldPrice: 950,
            newPrice: 900,
            color: "White",
            Available: true,
            Category: "laptop",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/lap (5).jpg"],
            about: "work laptop",
        },
        5: {
            name: "dell laptop",
            subHeader: "VISIT laptop STORE",
            subHeaderLink: "../products_5.html",
            rating: 5,
            oldPrice: 770,
            newPrice: 700,
            color: "Silver",
            Available: true,
            Category: "laptop",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/lap (6).jpg"],
            about: "for medium games",
        },
        6: {
            name: "asus rog",
            subHeader: "VISIT laptop STORE",
            subHeaderLink: "../products_5.html",
            rating: 5,
            oldPrice: 980,
            newPrice: 900,
            color: "Black",
            Available: true,
            Category: "laptop",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/lap (7).jpg"],
            about: "asus rog very powerd laptop",
        },
        7: {
            name: "asus rog laptop",
            subHeader: "VISIT laptop STORE",
            subHeaderLink: "../products_5.html",
            rating: 4,
            oldPrice: 900,
            newPrice: 800,
            color: "Black",
            Available: true,
            Category: "laptop",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/lap (8).jpg"],
            about: "for heavy gaming",
        },
        8: {
            name: "alianware laptop",
            subHeader: "VISIT laptop STORE",
            subHeaderLink: "../products_5.html",
            rating: 3.8,
            oldPrice: 1199,
            newPrice: 1100,
            color: "Gray",
            Available: true,
            Category: "laptop",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/lap (9).jpg"],
            about: "one of the most powerfull laptop",
        },
    },
    6: {
        1: {
            name: "Chair 1",
            subHeader: "VISIT CHAIR STORE",
            subHeaderLink: "../products_6.html",
            rating: 3.5,
            oldPrice: 10,
            newPrice: 8,
            color: "Brown",
            Available: true,
            Category: "Chair",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/ch1.jpg"],
            about: "This is a wooden chair",
        },
        2: {
            name: "Chair 2",
            subHeader: "VISIT CHAIR STORE",
            subHeaderLink: "../products_6.html",
            rating: 4,
            oldPrice: 12,
            newPrice: 10,
            color: "Coffee",
            Available: true,
            Category: "Chair",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/ch2.jpg"],
            about: "This is a wheel chair",
        },
        3: {
            name: "ًChair 3",
            subHeader: "VISIT CHAIR STORE",
            subHeaderLink: "../products_6.html",
            rating: 5,
            oldPrice: 15,
            newPrice: 12,
            color: "Brown",
            Available: true,
            Category: "Chair",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/ch3.jpg"],
            about: "This is a wooden set",
        },
        4: {
            name: "Chair 4",
            subHeader: "VISIT CHAIR STORE",
            subHeaderLink: "../products_6.html",
            rating: 2.5,
            oldPrice: 15,
            newPrice: 12,
            color: "Coffee",
            Available: true,
            Category: "Chair",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/ch4.jpg"],
            about: "This is a small chair",
        },
        5: {
            name: "Chair 5",
            subHeader: "VISIT CHAIR STORE",
            subHeaderLink: "../products_6.html",
            rating: 4.5,
            oldPrice: 19,
            newPrice: 17,
            color: "Brown",
            Available: true,
            Category: "Chair",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/ch5.jpg"],
            about: "This is a modern chair",
        },
        6: {
            name: "Chair 6",
            subHeader: "VISIT CHAIR STORE",
            subHeaderLink: "../products_6.html",
            rating: 4,
            oldPrice: 18,
            newPrice: 16,
            color: "Gray",
            Available: true,
            Category: "Chair",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/ch6.jpg"],
            about: "This is a wooden table",
        },
        7: {
            name: "Chair 7",
            subHeader: "VISIT CHAIR STORE",
            subHeaderLink: "../products_6.html",
            rating: 5,
            oldPrice: 10,
            newPrice: 18,
            color: "Orange",
            Available: true,
            Category: "Chair",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/ch7.jpg"],
            about: "This is a wooden table",
        },
        8: {
            name: "Chair 8",
            subHeader: "VISIT CHAIR STORE",
            subHeaderLink: "../products_6.html",
            rating: 2,
            oldPrice: 22,
            newPrice: 17,
            color: "White",
            Available: true,
            Category: "Chair",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/ch8.jpg"],
            about: "This is a wooden table",
        },
    },
    7: {
        1: {
            name: "Lamp 1",
            subHeader: "VISIT Lamp STORE",
            subHeaderLink: "../products_7.html",
            rating: 3.5,
            oldPrice: 10,
            newPrice: 8,
            color: "Brown",
            Available: true,
            Category: "Lamp",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Lamp 1.jpg"],
            about: "This is a wooden chair",
        },
        2: {
            name: "Lamp 2",
            subHeader: "VISIT Lamp STORE",
            subHeaderLink: "../products_7.html",
            rating: 4,
            oldPrice: 12,
            newPrice: 10,
            color: "Coffee",
            Available: true,
            Category: "Lamp",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Lamp 2.jpg"],
            about: "This is a wheel chair",
        },
        3: {
            name: "ًLamp 3",
            subHeader: "VISIT Lamp STORE",
            subHeaderLink: "../products_7.html",
            rating: 5,
            oldPrice: 15,
            newPrice: 12,
            color: "Brown",
            Available: true,
            Category: "Lamp",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Lamp 3.jpg"],
            about: "This is a wooden set",
        },
        4: {
            name: "Lamp 4",
            subHeader: "VISIT Lamp STORE",
            subHeaderLink: "../products_7.html",
            rating: 2.5,
            oldPrice: 15,
            newPrice: 12,
            color: "Coffee",
            Available: true,
            Category: "Lamp",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Lamp 4.jpg"],
            about: "This is a small chair",
        },
        5: {
            name: "Lamp 5",
            subHeader: "VISIT Lamp STORE",
            subHeaderLink: "../products_7.html",
            rating: 4.5,
            oldPrice: 19,
            newPrice: 17,
            color: "Brown",
            Available: true,
            Category: "Lamp",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Lamp 5.jpg"],
            about: "This is a modern chair",
        },
        6: {
            name: "Lamp 6",
            subHeader: "VISIT Lamp STORE",
            subHeaderLink: "../products_7.html",
            rating: 4,
            oldPrice: 18,
            newPrice: 16,
            color: "Gray",
            Available: true,
            Category: "Lamp",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Lamp 6.jpg"],
            about: "This is a wooden table",
        },
        7: {
            name: "Lamp 7",
            subHeader: "VISIT Lamp STORE",
            subHeaderLink: "../products_7.html",
            rating: 5,
            oldPrice: 10,
            newPrice: 18,
            color: "Orange",
            Available: true,
            Category: "Lamp",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Lamp 7.jpg"],
            about: "This is a wooden table",
        },
        8: {
            name: "Lamp 8",
            subHeader: "VISIT Lamp STORE",
            subHeaderLink: "../products_7.html",
            rating: 2,
            oldPrice: 22,
            newPrice: 17,
            color: "White",
            Available: true,
            Category: "Lamp",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Lamp 8.jpg"],
            about: "This is a wooden table",
        },
    },
    8: {
        1: {
            name: "Red Shoes",
            subHeader: "VISIT Shoes STORE",
            subHeaderLink: "../products_8.html",
            rating: 4,
            oldPrice: 11,
            newPrice: 10.5,
            color: "Red",
            Available: true,
            Category: "Shoes",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/shoe_1.jpg"],
            about: "made in vietnam 37:41",
        },
        2: {
            name: "Half Shoes",
            subHeader: "VISIT Shoes STORE",
            subHeaderLink: "../products_8.html",
            rating: 4.4,
            oldPrice: 20,
            newPrice: 19,
            color: "Blue",
            Available: true,
            Category: "Shoes",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/shoe_2.jpg"],
            about: "41-42",
        },
        3: {
            name: "ًMen Shoes",
            subHeader: "VISIT Shoes STORE",
            subHeaderLink: "../products_8.html",
            rating: 4,
            oldPrice: 30,
            newPrice: 29,
            color: "Brown",
            Available: true,
            Category: "Shoes",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/shoe_3.jpg"],
            about: "37-38-39-40-41",
        },
        4: {
            name: "Half Shoes",
            subHeader: "VISIT Shoes STORE",
            subHeaderLink: "../products_8.html",
            rating: 4.8,
            oldPrice: 35,
            newPrice: 32,
            color: "Gray",
            Available: true,
            Category: "Shoes",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/shoe_4.jpg"],
            about: "38-39-40",
        },
        5: {
            name: "Running Shoes",
            subHeader: "VISIT Shoes STORE",
            subHeaderLink: "../products_8.html",
            rating: 5,
            oldPrice: 17,
            newPrice: 15,
            color: "white",
            Available: true,
            Category: "Shoes",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/shoes.jpg"],
            about: "made in vietnam 37:41",
        },
        6: {
            name: "Black Shoes",
            subHeader: "VISIT Shoes STORE",
            subHeaderLink: "../products_8.html",
            rating: 5,
            oldPrice: 10,
            newPrice: 9,
            color: "Black",
            Available: true,
            Category: "Shoes",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Shoes_new.jpg"],
            about: "37:41",
        },
        7: {
            name: "Shoes for Girls",
            subHeader: "VISIT Shoes STORE",
            subHeaderLink: "../products_8.html",
            rating: 4,
            oldPrice: 22,
            newPrice: 20,
            color: "pink",
            Available: true,
            Category: "Shoes",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Shoes (3).jpg"],
            about: "made in vietnam 37:41",
        },
        8: {
            name: "New Balance Shoes",
            subHeader: "VISIT Shoes STORE",
            subHeaderLink: "../products_8.html",
            rating: 3.8,
            oldPrice: 19,
            newPrice: 15,
            color: "White",
            Available: true,
            Category: "Shoes",
            ShippingArea: "Worldwide",
            shippingFee: 2,
            quantity: 1,
            images: ["../images/Shoes_new2.jpg"],
            about: "41-42-43-44-45",
        },
    }
};

// Function to convert USD to Egyptian pounds
const convertToEGP = (usdPrice) => {
    const exchangeRate = 50; // 1 USD = 16.3 EGP
    return (usdPrice * exchangeRate).toFixed(2); // Rounded to 2 decimal places
};
let imgId = 0;
const slidingInterval = 4000;

const createImages = (images) => {
    const imgShowcase = document.querySelector(".img-showcase");
    images.forEach((image, index) => {
        const img = document.createElement("img");
        img.src = image;
        imgShowcase.appendChild(img);
    });
};

const slideImage = () => {
    const displayWidth = document.querySelector(
        ".img-showcase img:first-child"
    ).clientWidth;

    document.querySelector(".img-showcase").style.transform = `translateX(${-imgId * displayWidth
        }px)`;
};

const createRating = (rating) => {
    const intRating = Math.floor(rating);
    const decimalRating = rating - intRating;
    const ratingElement = document.querySelector(".product-rating");

    for (let i = 0; i < intRating; i++) {
        const star = document.createElement("i");
        star.classList.add("fas", "fa-star");
        ratingElement.appendChild(star);
    }
    if (decimalRating > 0) {
        const star = document.createElement("i");
        star.classList.add("fas", "fa-star-half-alt");
        ratingElement.appendChild(star);
    }

    for (let i = 0; i < 5 - Math.ceil(rating); i++) {
        const star = document.createElement("i");
        star.classList.add("far", "fa-star");
        ratingElement.appendChild(star);
    }
    const ratingText = ratingElement.querySelector("span");
    ratingText.innerHTML = rating;
};

const handleImages = (images) => {
    createImages(images);

    setInterval(() => {
        if (imgId === images.length - 1) {
            imgId = 0;
        } else {
            imgId++;
        }
        slideImage();
    }, slidingInterval);

    window.addEventListener("resize", slideImage);
};

const handleProductDetails = (product) => {
    const productDataElement = document.querySelector(".product-detail > ul");
    const productColorElement = productDataElement.querySelector("li:nth-child(1) > span");
    const productAvailabilityElement = productDataElement.querySelector("li:nth-child(2) > span");
    const productCategoryElement = productDataElement.querySelector("li:nth-child(3) > span");
    const productShippingAreaElement = productDataElement.querySelector("li:nth-child(4) > span");
    // const productShippingFeeElement = productDataElement.querySelector("li:nth-child(5) > span");

    productColorElement.innerHTML = product.color;
    productAvailabilityElement.innerHTML = product.Available ? "In Stock" : "Out of Stock";
    productCategoryElement.innerHTML = product.Category;
    productShippingAreaElement.innerHTML = product.ShippingArea;
    productShippingFeeElement.innerHTML = `$${product.shippingFee}`;
};

const changeProduct = (category_id, product_id) => {
    const product = products[category_id][product_id];

    const productNameElement = document.querySelector(".product-title");
    productNameElement.innerHTML = product.name;

    const productSubHeaderElement = document.querySelector("a.product-link");
    productSubHeaderElement.innerHTML = product.subHeader;
    productSubHeaderElement.href = product.subHeaderLink;

    const rating = product.rating;
    createRating(rating);
    handleImages(product.images);

    // Display prices in Egyptian pounds
    const oldPrice = document.querySelector(".last-price > span");
    const newPrice = document.querySelector(".new-price > span");

    oldPrice.innerHTML = `EGP ${convertToEGP(product.oldPrice)}`;
    newPrice.innerHTML = `EGP ${convertToEGP(product.newPrice)}`;

    // const oldPrice = document.querySelector(".last-price > span");
    // const newPrice = document.querySelector(".new-price > span");

    // oldPrice.innerHTML = `$${product.oldPrice}`;
    // newPrice.innerHTML = `$${product.newPrice}`;

    // Display shipping fee in Egyptian pounds
    const shippingFee = document.querySelector(".shipping-fee");
    shippingFee.innerHTML = convertToEGP(product.shippingFee);

    const productDetails = document.querySelector(".product-detail > p");
    // productDetails.innerHTML = product.about;
    handleProductDetails(product);

    const quantity = document.querySelector("body > div.card-wrapper > div > div.product-content > div.purchase-info > input[type=number]");
    quantity.value = product.quantity;
    quantity.addEventListener("change", () => {
        product.quantity = quantity.value;
        oldPrice.innerHTML = `$${product.oldPrice * quantity.value}`;
        newPrice.innerHTML = `$${product.newPrice * quantity.value}`;
    });
};

document.addEventListener("DOMContentLoaded", () => {
    const urlParams = new URLSearchParams(window.location.search);
    const category = urlParams.get("category");
    const product = urlParams.get("product");
    changeProduct(category, product);
});

